### ISSUE TITLE
Training material

### ISSUE THREAD

**Issue by danielsn** [model-checking/rmc#254]
Infra:

* [X] Tools and CI "Hello World" for the documentation #456 
* [ ] Extracting and testing the examples from the documentation #635

Docs:

* [X] Getting started guide #471
* [X] Installation guide #471
* [X] Comparison with other tools initial documentation #471
* [X] Using RMC on a single file #525
* [X] Using cargo-rmc #554
* [X] Developer documentation #572
* Migration of CBMC tutorial docs to RMC
  * [X] #474
  * [X] #481
  * [X] #494
  * [X] #525

**Comment by tedinski** [comment]
Here's the work for this issue:

Infra:

* [ ] Tools and CI "Hello World" for the documentation #456 
* [ ] Extracting and testing the examples from the documentation

Docs:

* [ ] Getting started guide
* [ ] Installation guide
* [ ] Comparison with other tools initial documentation
* [ ] Using RMC on a single file
* [ ] Using cargo-rmc
* [ ] Developer documentation
* [ ] Migration of CBMC tutorial docs to RMC
